# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8c5a4bcbdebcc3e4cb643e277f0d053cf913f8b9937c5eb1c79e0b46e89164b984838f5d89610e936af4921f0dbf9e5de21c18ce35c368e9e27e460251a7a91

test:
  secret_key_base: 785f64297f93e18a3c0c0371d4bff26b1c1f13a2c2b01f1b0471b1eba5da2c02c0c498e26f08aaa0778d8c65fa3f49cc308bde597b0255ae7f42c8926359f7b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
